name: Run Order Flow Analyzer

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # --- NEW, ROBUST VPN SETUP USING OFFICIAL TOOLS ---
      - name: Install and configure OpenVPN
        run: |
          # Step 1: Install the openvpn software package on the Ubuntu runner.
          # The 'sudo' command gives administrative privileges for installation.
          sudo apt-get update
          sudo apt-get install -y openvpn

          # Step 2: Write the .ovpn configuration from our secret into a file.
          echo "${{ secrets.OPENVPN_CONFIG }}" > protonvpn.ovpn

          # Step 3: Write the username and password into a separate auth file for security.
          # This is the standard way to provide credentials to the OpenVPN client.
          echo "${{ secrets.VPN_USERNAME }}" > auth.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> auth.txt

          # Step 4: Launch the OpenVPN client in the background.
          # 'sudo openvpn' runs the client with the necessary permissions.
          # '--config' specifies our configuration file.
          # '--auth-user-pass' tells it to read credentials from our auth file.
          # '--daemon' runs the process in the background so the workflow can continue.
          # '--log' writes the connection status to a log file for debugging.
          sudo openvpn --config protonvpn.ovpn --auth-user-pass auth.txt --daemon --log openvpn.log

          # Step 5: Wait a few seconds for the VPN connection to be fully established.
          sleep 5

          # Step 6 (Optional but recommended): Verify the connection.
          # This command fetches the current public IP address as seen by the outside world.
          # It should now be the IP of your VPN server, not the GitHub runner.
          echo "Verifying public IP address after VPN connection..."
          curl -s http://whatismyip.akamai.com/

      # The rest of the steps are the same as before and will now run through the VPN tunnel.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create API key file from secret
        run: echo "${{ secrets.CMC_API_KEY }}" > CoinMarketCapAPIKey.txt

      - name: Run the Order Flow Analyzer script
        run: python3 GITOrderFlowImbalanceAnalyzer.py
