name: Run Order Flow Analyzer

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install and configure OpenVPN
        run: |
          # Step 1: Install the openvpn software package.
          sudo apt-get update
          sudo apt-get install -y openvpn

          # Step 2: Write the .ovpn configuration from our secret into a temporary file.
          echo "${{ secrets.OPENVPN_CONFIG }}" > temp_config.ovpn

          # Step 3: Extract all inline keys/certs into separate files. This part was correct.
          awk '/<ca>/{flag=1; next} /<\/ca>/{flag=0} flag' temp_config.ovpn > ca.crt
          awk '/<key>/{flag=1; next} /<\/key>/{flag=0} flag' temp_config.ovpn > client.key
          awk '/<cert>/{flag=1; next} /<\/cert>/{flag=0} flag' temp_config.ovpn > client.crt
          awk '/<tls-auth>/{flag=1; next} /<\/tls-auth>/{flag=0} flag' temp_config.ovpn > tls.key
          
          # --- THIS IS THE CRITICAL FIX ---
          # Step 4: Create the final, clean config file by properly removing the entire
          # multi-line blocks, instead of just the tag lines.
          # We start with a copy and then use 'sed' to delete the blocks in-place.
          cp temp_config.ovpn protonvpn.ovpn
          sed -i '/<ca>/,/<\/ca>/d' protonvpn.ovpn
          sed -i '/<cert>/,/<\/cert>/d' protonvpn.ovpn
          sed -i '/<key>/,/<\/key>/d' protonvpn.ovpn
          sed -i '/<tls-auth>/,/<\/tls-auth>/d' protonvpn.ovpn

          # Step 5: Add the paths to the new key files into the clean config.
          echo -e "\nca ca.crt" >> protonvpn.ovpn
          echo "cert client.crt" >> protonvpn.ovpn
          echo "key client.key" >> protonvpn.ovpn
          echo "tls-auth tls.key 1" >> protonvpn.ovpn

          # Step 6: Write the username and password into a separate auth file.
          echo "${{ secrets.VPN_USERNAME }}" > auth.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> auth.txt

          # Step 7: Launch the OpenVPN client with the new, fully clean configuration.
          sudo openvpn --config protonvpn.ovpn --auth-user-pass auth.txt --daemon --log openvpn.log

          # Step 8: Wait for the connection to establish.
          sleep 8

          # Step 9: Verify the connection and check the log for success.
          echo "--- Verifying public IP address ---"
          curl -s http://whatismyip.akamai.com/
          echo "\n--- Checking VPN log for status (look for 'Initialization Sequence Completed') ---"
          tail -n 20 openvpn.log

      # The rest of the workflow continues as before.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create API key file from secret
        run: echo "${{ secrets.CMC_API_KEY }}" > CoinMarketCapAPIKey.txt

      - name: Run the Order Flow Analyzer script
        run: python3 GITOrderFlowImbalanceAnalyzer.py
