name: Run Order Flow Analyzer

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install and configure OpenVPN
        run: |
          # Step 1: Install the openvpn software package.
          sudo apt-get update
          sudo apt-get install -y openvpn

          # Step 2: Write the .ovpn configuration from our secret into a file.
          echo "${{ secrets.OPENVPN_CONFIG }}" > protonvpn.ovpn
          
          # --- THIS IS THE CRITICAL FIX ---
          # Step 2.1: Sanitize the config file by removing the first line,
          # which can sometimes contain non-standard metadata that causes errors.
          # The 'sed -i '1d'' command edits the file in-place and deletes the 1st line.
          sudo sed -i '1d' protonvpn.ovpn

          # Step 3: Write the username and password into a separate auth file.
          echo "${{ secrets.VPN_USERNAME }}" > auth.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> auth.txt

          # Step 4: Launch the OpenVPN client in the background.
          sudo openvpn --config protonvpn.ovpn --auth-user-pass auth.txt --daemon --log openvpn.log

          # Step 5: Wait for the VPN connection to be fully established.
          sleep 5

          # Step 6: Verify the connection and check the log for errors.
          echo "--- Verifying public IP address ---"
          curl -s http://whatismyip.akamai.com/
          echo "\n--- Checking VPN log for errors ---"
          # This will show the last few lines of the log, which is helpful for debugging.
          tail -n 10 openvpn.log

      # The rest of the steps are the same as before.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create API key file from secret
        run: echo "${{ secrets.CMC_API_KEY }}" > CoinMarketCapAPIKey.txt

      - name: Run the Order Flow Analyzer script
        run: python3 GITOrderFlowImbalanceAnalyzer.py
