name: Run Order Flow Analyzer

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # --- NEW STEP: ESTABLISH VPN CONNECTION ---
      # This step connects to your VPN before any Python code runs.
      # All subsequent network traffic will be routed through the VPN.
      - name: Start VPN connection
        uses: "social-medial-expert/openvpn-action@v1.2.2"
        with:
          CONFIG_DATA: ${{ secrets.OPENVPN_CONFIG }}
          USERNAME: ${{ secrets.VPN_USERNAME }}
          PASSWORD: ${{ secrets.VPN_PASSWORD }}

      # The rest of the steps are the same as before
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create API key file from secret
        run: echo "${{ secrets.CMC_API_KEY }}" > CoinMarketCapAPIKey.txt

      # This step will now run through the VPN
      - name: Run the Order Flow Analyzer script
        run: python3 GITOrderFlowImbalanceAnalyzer.py
