name: Swing High Rejection Detector

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow on a schedule
  schedule:
    # This will run every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install and configure OpenVPN
        run: |
          # Set flags to exit on error and print commands
          set -ex

          # Step 1: Install OpenVPN
          echo "--- 1. Installing OpenVPN ---"
          sudo apt-get update
          sudo apt-get install -y openvpn

          # Step 2: Write the .ovpn configuration from the secret.
          echo "${{ secrets.OPENVPN_CONFIG }}" > protonvpn.ovpn

          # Step 3: Write the username and password into a separate auth file.
          echo "${{ secrets.VPN_USERNAME }}" > auth.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> auth.txt

          # Step 4: Modify the main config file to use our auth file.
          echo "--- 4. Modifying config to use auth.txt ---"
          echo "auth-user-pass auth.txt" >> protonvpn.ovpn
          
          # Step 5: Launch the OpenVPN client as a background daemon.
          echo "--- 5. Launching OpenVPN client ---"
          sudo openvpn --config protonvpn.ovpn --daemon --log openvpn.log

          # Step 6: Wait for the connection to establish with a robust loop.
          echo "--- 6. Waiting for VPN to establish (max 60s) ---"
          timeout=60
          start_time=$(date +%s)
          while ! sudo grep -q "Initialization Sequence Completed" openvpn.log; do
              current_time=$(date +%s)
              elapsed_time=$((current_time - start_time))
              if [ $elapsed_time -gt $timeout ]; then
                  echo "Error: Timed out after ${timeout}s waiting for VPN connection."
                  echo "--- Final OpenVPN Log ---"
                  sudo cat openvpn.log
                  exit 1
              fi
              sleep 2
          done
          echo "--- VPN connection established successfully. ---"

          # Step 7: Final verification.
          echo "--- 7. Final Verification ---"
          echo "--- Checking VPN log for status (look for 'Initialization Sequence Completed') ---"
          sudo cat openvpn.log
          echo "--- Verifying public IP address ---"
          curl --fail http://whatismyip.akamai.com/ || (echo "Curl failed, VPN did not connect. See log above." && exit 1)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the Swing High Rejection Detector script
        run: python3 SwingHighRejectionDetector.py
