name: Run Order Flow Analyzer

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install and configure OpenVPN
        run: |
          # Set flags to exit on error and print commands for debugging
          set -ex

          # Step 1: Install the openvpn software package.
          echo "--- 1. Installing OpenVPN ---"
          sudo apt-get update
          sudo apt-get install -y openvpn

          # Step 2: Write the .ovpn configuration directly from the secret.
          echo "--- 2. Writing secret to protonvpn.ovpn ---"
          echo "${{ secrets.OPENVPN_CONFIG }}" > protonvpn.ovpn

          # Step 3: Write the username and password into a separate auth file.
          echo "--- 3. Creating auth.txt file ---"
          echo "${{ secrets.VPN_USERNAME }}" > auth.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> auth.txt

          # --- THIS IS THE CRITICAL FIX ---
          # Step 4: Modify the main config file to tell it to use our auth file.
          # The 'auth-user-pass' directive inside the file makes this connection.
          echo "--- 4. Modifying config to use auth.txt ---"
          echo "auth-user-pass auth.txt" >> protonvpn.ovpn
          
          # --- DIAGNOSTIC STEP: SHOW THE FINAL CONFIG BEFORE LAUNCH ---
          echo "--- 4.1. Displaying final protonvpn.ovpn before launch ---"
          cat protonvpn.ovpn
          echo "--- End of final config display ---"

          # Step 5: Launch the OpenVPN client. We no longer pass '--auth-user-pass' on the command line,
          # as the config file now handles it internally.
          echo "--- 5. Launching OpenVPN client ---"
          sudo openvpn --config protonvpn.ovpn --daemon --log openvpn.log

          # Step 6: Wait for the connection to establish.
          echo "--- 6. Waiting for VPN to establish ---"
          sleep 10

          # Step 7: Final verification.
          echo "--- 7. Final Verification ---"
          echo "--- Checking VPN log for status (look for 'Initialization Sequence Completed') ---"
          cat openvpn.log
          echo "--- Verifying public IP address ---"
          curl --fail http://whatismyip.akamai.com/ || (echo "Curl failed, VPN did not connect. See log above." && exit 1)

      # The rest of the workflow continues as before.
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create API key file from secret
        run: echo "${{ secrets.CMC_API_KEY }}" > CoinMarketCapAPIKey.txt

      - name: Run the Order Flow Analyzer script
        run: python3 GITOrderFlowImbalanceAnalyzer.py
