name: Run Order Flow Analyzer

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # --- NEW, CORRECTED VPN STEP ---
      # This uses a more stable and popular community action to connect to the VPN.
      # The input names (CONFIG, USERNAME, PASSWORD) are in uppercase.
      - name: Start VPN connection
        uses: "spheramid/openvpn-github-action@v2.0.0"
        with:
          CONFIG_DATA: ${{ secrets.OPENVPN_CONFIG }}
          USERNAME: ${{ secrets.VPN_USERNAME }}
          PASSWORD: ${{ secrets.VPN_PASSWORD }}
          # This is an optional but good addition to see if the VPN connected successfully.
          VERIFY: 'true'

      # The rest of the steps are the same as before
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create API key file from secret
        run: echo "${{ secrets.CMC_API_KEY }}" > CoinMarketCapAPIKey.txt

      # This step will now run through the new VPN action
      - name: Run the Order Flow Analyzer script
        run: python3 GITOrderFlowImbalanceAnalyzer.py
